kind: pipeline
name: sanke

platform:
  os: linux
  arch: arm64

steps:
- name: build
  image: golang
  commands:
  - go build
  - go test -short
  when:
    event:
    - push

- name: integration
  image: golang
  commands:
  - go test -v
  when:
    event:
    - push